openapi: 3.1.0
info:
  title: Guardar Conversacion GPT (Proxy Vercel)
  version: 1.0.0
servers:
  - url: https://TU-PROXY.vercel.app/api
paths:
  /guardarConversacion:
    post:
      operationId: guardarConversacion
      summary: Guarda pregunta y respuesta vía Proxy en Google Sheets
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                pregunta:
                  type: string
                respuesta:
                  type: string
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
